In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('median_odds.csv')

In [6]:
df

,Unnamed: 0,game_id,home_team,away_team,commence_time,id,game_date,season,home_score,away_score,...,betus_away,betus_home,wynnbet_away,wynnbet_home,circasports_away,circasports_home,superbook_away,superbook_home,unibet_us_away,unibet_us_home
0,0,d18bceb2663d46029f10157b97e706b4,Washington Nationals,New York Yankees,2020-07-23T23:08:00Z,9056,2020-07-23 00:00:00.000000,2020,1,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,761f244afb0826308e05516d7ee62028,Los Angeles Dodgers,San Francisco Giants,2020-07-24T02:08:00Z,9057,2020-07-23 00:00:00.000000,2020,8,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,d18bceb2663d46029f10157b97e706b4,Washington Nationals,New York Yankees,2020-07-23T23:08:00Z,9056,2020-07-23 00:00:00.000000,2020,1,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,761f244afb0826308e05516d7ee62028,Los Angeles Dodgers,San Francisco Giants,2020-07-24T02:08:00Z,9057,2020-07-23 00:00:00.000000,2020,8,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,5362faebd839aba16645925fd2877f16,New York Mets,Atlanta Braves,2020-07-24T20:10:00Z,9058,2020-07-24 00:00:00.000000,2020,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3301,3301,c56ebf255ed5b3905fb4c2cd32fb1eca,Colorado Rockies,Arizona Diamondbacks,2023-04-30T19:10:00Z,924,2023-04-30 00:00:00.000000,2023,12,4,...,-9.5,-9.5,-9.5,-9.5,-9.5,-9.5,-9.5,-9.5,-9.5,-9.5
3302,3302,8571d48f75d0ade68b3897ca6319394d,San Diego Padres,San Francisco Giants,2023-04-30T20:05:00Z,925,2023-04-30 00:00:00.000000,2023,6,4,...,-7.0,-7.0,-7.0,-7.0,-7.0,-7.0,-7.0,-7.0,-7.0,-7.0
3303,3303,793fd4271c4b703b7384c05e399f62f7,Oakland Athletics,Cincinnati Reds,2023-04-30T20:07:00Z,926,2023-04-30 00:00:00.000000,2023,5,4,...,-13.5,-13.5,-13.5,-13.5,-13.5,-13.5,-13.5,-13.5,-13.5,-13.5
3304,3304,75214037c234afa2564a0cf70be6856b,Los Angeles Dodgers,St. Louis Cardinals,2023-04-30T20:10:00Z,927,2023-04-30 00:00:00.000000,2023,6,3,...,-9.5,-9.5,-9.5,-9.5,-9.5,-9.5,-9.5,-9.5,-9.5,-9.5
3305,3305,d8c3479002d2c2cc382b18fcad4eeff9,Houston Astros,Philadelphia Phillies,2023-04-30T23:10:00Z,928,2023-04-30 00:00:00.000000,2023,4,3,...,-11.5,-11.5,-11.5,-11.5,-11.5,-11.5,-11.5,-11.5,-11.5,-11.5